BEGIN TRANSACTION;
CREATE TABLE SALESPERSON (ID INTEGER PRIMARY KEY AUTOINCREMENT,NAME TEXT,CONTACTNO INTEGER);
CREATE TABLE PARTY_TRANSACTION (ID	INTEGER PRIMARY KEY AUTOINCREMENT,T_DATE TEXT,T_AMOUNT REAL,SALES_PERSON_ID INTEGER,PARTY_ID INTEGER,DB_SYNC INTEGER DEFAULT 0,RECIEPT_NO TEXT NOT NULL, BILL_NO TEXT NOT NULL);
CREATE TABLE PARTY (ID INTEGER PRIMARY KEY AUTOINCREMENT,NAME TEXT,STREET TEXT,CITY TEXT,STATE TEXT,COUNTRY TEXT,POSTAL_CODE INTEGER,CONTACT_NO INTEGER);
CREATE TABLE LOCATION (ID INTEGER PRIMARY KEY AUTOINCREMENT,L_TIME TEXT,LATITUDE FLOAT,LONGITUDE FLOAT,DB_SYNC INTEGER DEFAULT 0);
COMMIT;
